// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A natural language deal query AI agent.
 *
 * - askDealBot - A function that handles the deal query process.
 * - AskDealBotInput - The input type for the askDealBot function.
 * - AskDealBotOutput - The return type for the askDealBot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AskDealBotInputSchema = z.object({
  query: z.string().describe('The natural language query for finding deals.'),
});
export type AskDealBotInput = z.infer<typeof AskDealBotInputSchema>;

const AskDealBotOutputSchema = z.object({
  response: z.string().describe('The AI-generated response to the deal query.'),
});
export type AskDealBotOutput = z.infer<typeof AskDealBotOutputSchema>;

export async function askDealBot(input: AskDealBotInput): Promise<AskDealBotOutput> {
  return askDealBotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'askDealBotPrompt',
  input: {schema: AskDealBotInputSchema},
  output: {schema: AskDealBotOutputSchema},
  prompt: `You are a helpful AI assistant specializing in finding deals and product recommendations on Indian e-commerce platforms like Amazon, Flipkart, Myntra, and Ajio.

  A user will ask a question about deals. Use your knowledge of available products, discounts, coupons, and cashback offers to provide the best possible recommendations.

  User query: {{{query}}}`,
});

const askDealBotFlow = ai.defineFlow(
  {
    name: 'askDealBotFlow',
    inputSchema: AskDealBotInputSchema,
    outputSchema: AskDealBotOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
